name: spotify_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.5
  open_url: ^2.0.0
  shelf: ^1.4.0

dev_dependencies:
  test: ^1.21.6
  very_good_analysis: ^3.1.0
